server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://dev-db-server:3306/myapp_local
    username: local_user
    password: local_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: INFO
    com.myapp: DEBUG

app:
  name: MySpringBootApp-local
  description: "Local environment configuration."
