server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://dev-db-server:3306/myapp_dev
    username: dev_user
    password: dev_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  profiles:
    active: dev

logging:
  level:
    root: INFO
    com.myapp: DEBUG

app:
  name: MySpringBootApp-Dev
  description: "Development environment configuration."
