server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myapp
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: local

logging:
  level:
    root: INFO
    com.myapp: DEBUG

app:
  name: MySpringBootApp
  description: "This is a sample Spring Boot application."
