server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myapp-dev
    username: dev_user
    password: dev_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: local

logging:
  level:
    root: INFO
    com.myapp: DEBUG

app:
  name: MySpringBootApp-dev
  description: "This is a sample dev Spring Boot application."
