server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/myapp_prd
    username: prod_user
    password: prod_pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  profiles:
    active: prd

logging:
  level:
    root: ERROR
    com.myapp: WARN

app:
  name: MySpringBootApp-prd
  description: "Production environment configuration."
